# Generated by Django 5.0.3 on 2024-04-26 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='komerc',
            options={'managed': False, 'ordering': ['-pk']},
        ),
    ]
